version: '3.8'

services:
  playbot:
    build: .
    image: playbot:latest
    container_name: playbot
    restart: unless-stopped

    # Environment variables from .env file
    env_file:
      - .env

    # Expose port 8080 for the web API and admin panel
    ports:
      - "8080:8080"

    # Mount logs and data directories to persist on host
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

    # Resource limits (adjust based on your Docker host)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          memory: 512M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
